### PR TITLE
12 webgl build

### LINKED ISSUE #12: Library brakes WebGL build
During development of LD49 game we spotted that the library issues some problems with WebGL. Due to a lack of time we didn't check what's wrong with it. So we have to investigate & fix the issue

### PR DESCRIPTION
**Pull request by erlioniel**
Resolves #12 
Partially related to #11 

- Weak references for receiver object
- Some refactoring for better lib isolation
- Removing unnecessary parts of Tact
- Adding documentation about `link.xml`
- Adding simple scene to be able to build & test project

### CODE REVIEW

File: Assets/Scripts/TestCatcher.cs [hunk 1]
```diff
@@ -0,0 +1,20 @@
+using DefaultNamespace;
+using RainbowDuckGames.UnityEntitySignals;
+using RainbowDuckGames.UnityEntitySignals.Handlers;
+using UnityEngine;
+
+[RequireComponent(typeof(SpriteRenderer))]
+public class TestCatcher : MonoBehaviour {
+    void OnEnable() {
+        Global.Signals.On().Add((ESHandler<TestEmitter.ColorSignal>) OnSignal);
```
Comment (RaMoNVicious) [inline Assets/Scripts/TestCatcher.cs]: Why not `Global.Signals.On().Add(this);` ?

**Review by RaMoNVicious — APPROVED** [review]
